// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsdWKTJISPuXZ_yGcngXDwa39yFg6zywc',
    appId: '1:471509767704:web:a0db9b82fe71ab0353556d',
    messagingSenderId: '471509767704',
    projectId: 'clothsonrent-8ae63',
    authDomain: 'clothsonrent-8ae63.firebaseapp.com',
    storageBucket: 'clothsonrent-8ae63.appspot.com',
    measurementId: 'G-M4124YBHE8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyGEC6sYzGH-59YCNvigq_gB2-Vj1vclA',
    appId: '1:471509767704:android:7a52d13259a7aa1553556d',
    messagingSenderId: '471509767704',
    projectId: 'clothsonrent-8ae63',
    storageBucket: 'clothsonrent-8ae63.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSxE-AoTc2UduABD2t8iUQpi6_p0fIf0I',
    appId: '1:471509767704:ios:8b3c06e8ae25590053556d',
    messagingSenderId: '471509767704',
    projectId: 'clothsonrent-8ae63',
    storageBucket: 'clothsonrent-8ae63.appspot.com',
    iosBundleId: 'com.example.clothsonrent',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSxE-AoTc2UduABD2t8iUQpi6_p0fIf0I',
    appId: '1:471509767704:ios:7d557c7666ed7e0d53556d',
    messagingSenderId: '471509767704',
    projectId: 'clothsonrent-8ae63',
    storageBucket: 'clothsonrent-8ae63.appspot.com',
    iosBundleId: 'com.example.clothsonrent.RunnerTests',
  );
}
